# Generated by Django 5.0 on 2024-10-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, null=True, verbose_name='Label')),
                ('upper_limit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Upper Limit')),
                ('lower_limit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Lower Limit')),
                ('remark', models.CharField(max_length=50, null=True, verbose_name='Remark')),
                ('schools', models.ManyToManyField(to='api.school', verbose_name='Schools Using This Grading System')),
            ],
            options={
                'unique_together': {('label', 'upper_limit', 'lower_limit', 'remark')},
            },
        ),
    ]
