# Generated by Django 5.0 on 2023-12-29 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_department', to='api.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='api.subject', verbose_name='Subject(s) taught'),
        ),
    ]
