# Generated by Django 5.0 on 2024-10-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gradingsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='Total Exams Score'),
        ),
    ]
