# Generated by Django 5.0 on 2024-05-02 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=500, verbose_name='Reply')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='At')),
                ('replying_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.message', verbose_name='Replying To')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
        ),
    ]
