# Generated by Django 5.0 on 2024-05-02 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_replymessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='replymessages',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='replymessages',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='from_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_head', to='api.head', verbose_name='From Head'),
        ),
        migrations.AddField(
            model_name='message',
            name='from_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_staff', to='api.staff', verbose_name='From Staff'),
        ),
        migrations.AddField(
            model_name='message',
            name='from_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_student', to='api.student', verbose_name='From Student'),
        ),
        migrations.AddField(
            model_name='message',
            name='replies',
            field=models.ManyToManyField(related_name='reply', to='api.replymessages', verbose_name='Replies'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_head',
            field=models.ManyToManyField(related_name='to_head', to='api.head', verbose_name='To Head'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_staff',
            field=models.ManyToManyField(related_name='to_staff', to='api.staff', verbose_name='To Staff'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_student',
            field=models.ManyToManyField(related_name='to_student', to='api.student', verbose_name='To Student'),
        ),
        migrations.AddField(
            model_name='replymessages',
            name='content',
            field=models.CharField(default='null', max_length=500, verbose_name='Reply Message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replymessages',
            name='from_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_from_head', to='api.head', verbose_name='From Head'),
        ),
        migrations.AddField(
            model_name='replymessages',
            name='from_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_from_staff', to='api.staff', verbose_name='From Staff'),
        ),
        migrations.AddField(
            model_name='replymessages',
            name='from_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_from_student', to='api.student', verbose_name='From Student'),
        ),
    ]
