# Generated by Django 5.0 on 2024-05-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_message_receiver_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReplyMessages',
            new_name='ReplyMessage',
        ),
        migrations.RemoveField(
            model_name='message',
            name='replies',
        ),
    ]
