# Generated by Django 5.0 on 2023-12-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(default='not set', max_length=50, verbose_name='Religion'),
        ),
    ]
