# Generated by Django 5.0 on 2024-10-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_staff_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
    ]
