# Generated by Django 5.0 on 2024-05-03 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_replymessages_replymessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replies',
            field=models.ManyToManyField(related_name='reply', to='api.replymessage', verbose_name='Replies'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 3), verbose_name='Attendance Date'),
        ),
    ]
