# Generated by Django 5.0 on 2023-12-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_religion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_years',
        ),
    ]
