# Generated by Django 5.0 on 2024-05-06 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_message_replies_alter_studentattendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='replies',
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 6), verbose_name='Attendance Date'),
        ),
        migrations.DeleteModel(
            name='ReplyMessage',
        ),
    ]
