# Generated by Django 5.0 on 2023-12-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_student_academic_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='graduation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='has_graduated',
        ),
        migrations.AddField(
            model_name='classe',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='has_completed',
            field=models.BooleanField(default=False, verbose_name='Has Completed'),
        ),
    ]
