# Generated by Django 5.0 on 2024-05-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_message_replies_alter_studentattendance_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Notification',
        ),
    ]
