# Generated by Django 5.0 on 2023-12-30 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_student_graduation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.batch', verbose_name='Students Batch'),
        ),
    ]
