# Generated by Django 5.0 on 2023-12-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_classe_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='head_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Head ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Staff ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_id',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Student ID.'),
        ),
    ]
