# Generated by Django 5.0 on 2024-05-07 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_message_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='to_head',
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 7), verbose_name='Attendance Date'),
        ),
    ]
