# Generated by Django 5.0 on 2024-06-06 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_notification_to_head_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Program Name')),
                ('degree', models.CharField(max_length=500, verbose_name='Degree')),
                ('knust_cut_off_point', models.CharField(blank=True, max_length=500, null=True, verbose_name='KNUST cut-off point')),
                ('ug_cut_off_point', models.CharField(blank=True, max_length=500, null=True, verbose_name='Legon(UG) cut-off point')),
                ('uds_cut_off_point', models.CharField(blank=True, max_length=500, null=True, verbose_name='UDS cut-off point')),
                ('ucc_cut_off_point', models.CharField(blank=True, max_length=500, null=True, verbose_name='UCC cut-off point')),
                ('apsa_cut_off_point', models.CharField(blank=True, max_length=500, null=True, verbose_name='APSA cut-off point')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to='F:\\PRO\\Git_Repository\\cassandra\\Backend\\staticfiles\\files'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 6), verbose_name='Attendance Date'),
        ),
    ]
