# Generated by Django 5.0 on 2024-10-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_school_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='academic_years',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='date_enrolled',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='students_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_years',
            field=models.ManyToManyField(to='api.academicyear', verbose_name='Academic Years'),
        ),
    ]
