# Generated by Django 5.0 on 2024-06-07 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_universityprogram_alter_file_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnustProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Program Name')),
                ('degree', models.CharField(max_length=500, verbose_name='Degree')),
                ('cut_off_point', models.CharField(blank=True, max_length=500, null=True, verbose_name='KNUST cut-off point')),
            ],
        ),
        migrations.DeleteModel(
            name='UniversityProgram',
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 7), verbose_name='Attendance Date'),
        ),
    ]
