# Generated by Django 5.0 on 2023-12-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alt_contact',
            field=models.CharField(blank=True, default='not set', max_length=15, null=True, verbose_name='Alternate Phone No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_nationality',
            field=models.CharField(default='GHANA', max_length=50, verbose_name='Nationality of Guardian'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='GHANA', max_length=50, verbose_name='Nationality'),
        ),
    ]
