# Generated by Django 5.0 on 2024-10-26 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_student_repeated'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_class', to='api.classe', verbose_name='From Class Name')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school', verbose_name='School')),
                ('to_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_class', to='api.classe', verbose_name='To Class Name')),
            ],
        ),
    ]
