# Generated by Django 5.0 on 2023-12-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_student_alt_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='date_enrolled',
            field=models.DateField(null=True, verbose_name='Enrollment Date'),
        ),
    ]
