# Generated by Django 5.0 on 2024-06-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_knustprogram_delete_universityprogram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Program Name')),
                ('degree', models.CharField(max_length=500, verbose_name='Degree')),
                ('cut_off_point_choice_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='First choice cut-off point')),
                ('cut_off_point_choice_2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Second choice cut-off point')),
                ('subject_requirement', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subject requirement')),
            ],
        ),
        migrations.AlterField(
            model_name='knustprogram',
            name='cut_off_point',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Cut-off point'),
        ),
    ]
