# Generated by Django 5.0 on 2024-10-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_linkedclasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='linked_classes',
            field=models.ManyToManyField(to='api.linkedclasse', verbose_name='Linked Classes'),
        ),
        migrations.AddField(
            model_name='student',
            name='repeated_academic_years',
            field=models.ManyToManyField(related_name='repeated_academic_years', to='api.academicyear', verbose_name='Repeated Academic Years'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_years',
            field=models.ManyToManyField(related_name='academic_years', to='api.academicyear', verbose_name='Academic Years'),
        ),
    ]
