# Generated by Django 5.0 on 2024-01-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_classe_date_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_enrolled',
            field=models.DateField(blank=True, null=True, verbose_name='Enrollment Date'),
        ),
    ]
