# Generated by Django 5.0 on 2024-10-26 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_student_linked_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='students_graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date students will graduated'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduation_class', to='api.classe', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Graduated'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_class', to='api.classe', verbose_name='Class'),
        ),
    ]
