# Generated by Django 5.0 on 2024-06-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_uccprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='School Name')),
                ('aka', models.CharField(max_length=500, verbose_name='Short Name')),
            ],
        ),
    ]
