# Generated by Django 5.0 on 2024-10-26 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_academicyear_students_graduation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='head_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff', verbose_name='Head Teacher'),
        ),
    ]
