# Generated by Django 5.0 on 2024-06-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name of University '),
        ),
    ]
