# Generated by Django 5.0 on 2024-01-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_head_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='School Name')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='School Code')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='School Address')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='School Short Name')),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal Code')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to='F:\\PRO\\Git_Repository\\school-management-system\\Backend\\staticfiles\\files'),
        ),
    ]
