# Generated by Django 5.0 on 2024-10-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_classe_head_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='alt_contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.CharField(default='none', max_length=100, verbose_name='Guardian Name'),
        ),
    ]
