# Generated by Django 5.0 on 2024-09-07 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_academicyear_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 7), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='head',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 7), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='program',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 7), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='result',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 7), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='school',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 7), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 7), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 7), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='subject',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 7), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 7), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='head',
            name='address',
            field=models.CharField(default='none', max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='head',
            name='alt_contact',
            field=models.CharField(blank=True, default='none', max_length=15, null=True, verbose_name='Alternate Phone No'),
        ),
        migrations.AlterField(
            model_name='head',
            name='contact',
            field=models.CharField(default='none', max_length=20, verbose_name='Phone No'),
        ),
        migrations.AlterField(
            model_name='head',
            name='gender',
            field=models.CharField(default='none', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='head',
            name='pob',
            field=models.CharField(default='none', max_length=50, verbose_name='Home City/Town'),
        ),
        migrations.AlterField(
            model_name='head',
            name='region',
            field=models.CharField(default='none', max_length=50, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(default='none', max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='alt_contact',
            field=models.CharField(blank=True, default='none', max_length=15, null=True, verbose_name='Alternate Phone No'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.CharField(default='none', max_length=20, verbose_name='Phone No'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(default='none', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pob',
            field=models.CharField(default='none', max_length=50, verbose_name='Home City/Town'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='region',
            field=models.CharField(default='none', max_length=50, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='none', max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='alt_contact',
            field=models.CharField(blank=True, default='none', max_length=15, null=True, verbose_name='Alternate Phone No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(default='none', max_length=20, verbose_name='Phone No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian',
            field=models.CharField(default='none', max_length=100, verbose_name='Guardian Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_address',
            field=models.CharField(default='none', max_length=100, verbose_name='Address of guardian'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_contact',
            field=models.CharField(default='none', max_length=10, verbose_name='Phone no. of guardian'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_email',
            field=models.CharField(default='none', max_length=100, verbose_name='Guardian Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_occupation',
            field=models.CharField(default='none', max_length=50, verbose_name='Occupation of guardian'),
        ),
        migrations.AlterField(
            model_name='student',
            name='index_no',
            field=models.CharField(default='none', max_length=20, verbose_name='Index No.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pob',
            field=models.CharField(default='none', max_length=50, verbose_name='Home City/Town'),
        ),
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(default='none', max_length=50, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(default='none', max_length=50, verbose_name='Religion'),
        ),
    ]
