# Generated by Django 5.0 on 2024-01-03 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_school_alter_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school', verbose_name='School'),
        ),
        migrations.AddField(
            model_name='batch',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school', verbose_name='School'),
        ),
        migrations.AddField(
            model_name='classe',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school', verbose_name='School'),
        ),
        migrations.AddField(
            model_name='department',
            name='schools',
            field=models.ManyToManyField(blank=True, to='api.school', verbose_name='Schools'),
        ),
        migrations.AddField(
            model_name='head',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school', verbose_name='School'),
        ),
        migrations.AddField(
            model_name='program',
            name='schools',
            field=models.ManyToManyField(blank=True, to='api.school', verbose_name='Schools'),
        ),
        migrations.AddField(
            model_name='result',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school', verbose_name='School'),
        ),
        migrations.AddField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school', verbose_name='School'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school', verbose_name='School'),
        ),
        migrations.AddField(
            model_name='subject',
            name='schools',
            field=models.ManyToManyField(blank=True, to='api.school', verbose_name='Schools'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school', verbose_name='School'),
        ),
    ]
