# Generated by Django 5.0 on 2024-10-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_student_alt_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='schools',
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Program Name'),
        ),
    ]
