# Generated by Django 5.0 on 2024-01-03 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_academicyear_school_batch_school_classe_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='sem_1_end_date',
            field=models.DateField(null=True, verbose_name='First Semester End Date'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='sem_1_start_date',
            field=models.DateField(null=True, verbose_name='First Semester Start Date'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='sem_2_end_date',
            field=models.DateField(null=True, verbose_name='Second Semester End Date'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='sem_2_start_date',
            field=models.DateField(null=True, verbose_name='Second Semester Start Date'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='sem_3_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Third Semester End Date'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='sem_3_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Third Semester Start Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.batch', verbose_name='Batch'),
        ),
    ]
