# Generated by Django 5.0 on 2024-01-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_academicyear_sem_1_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='head',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='head',
            name='head_id',
            field=models.CharField(max_length=50, verbose_name='Head ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=50, verbose_name='Staff ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_id',
            field=models.CharField(max_length=50, null=True, verbose_name='Student ID.'),
        ),
        migrations.AlterUniqueTogether(
            name='head',
            unique_together={('head_id', 'school', 'dob', 'contact', 'address')},
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('staff_id', 'school', 'dob', 'contact', 'address')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('st_id', 'school')},
        ),
    ]
