# Generated by Django 5.0 on 2024-10-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_staff_address_alter_staff_alt_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicyear',
            old_name='number_of_divisions',
            new_name='no_divisions',
        ),
    ]
