# Generated by Django 5.0 on 2024-09-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_student_st_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='head_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Head ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Staff ID'),
        ),
    ]
