# Generated by Django 5.0 on 2024-01-04 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_head_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='schools',
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school', verbose_name='School'),
        ),
    ]
