# Generated by Django 5.0 on 2024-09-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_head_head_id_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='head_id',
            field=models.CharField(default='none', max_length=50, verbose_name='Head ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default='none', max_length=50, verbose_name='Staff ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_id',
            field=models.CharField(default='none', max_length=50, verbose_name='Student ID.'),
        ),
    ]
