# Generated by Django 5.0 on 2024-01-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_department_schools_department_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(default='not set', max_length=100, verbose_name='School Address'),
        ),
    ]
