# Generated by Django 5.0 on 2024-01-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_school_postal_code_alter_school_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
