# Generated by Django 5.0 on 2024-09-08 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_educationallevel_alter_academicyear_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.educationallevel', verbose_name='Educational Level'),
        ),
        migrations.AddField(
            model_name='staff',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.educationallevel', verbose_name='Educational Level'),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.educationallevel', verbose_name='Educational Level'),
        ),
    ]
