# Generated by Django 5.0 on 2024-10-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_student_graduation_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduatedClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Class Name')),
                ('students_year', models.IntegerField(default=1, verbose_name='Students Year')),
                ('head_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff', verbose_name='Head Teacher')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.program', verbose_name='Students Program')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school', verbose_name='School')),
                ('students', models.ManyToManyField(blank=True, to='api.student', verbose_name='Students')),
                ('subjects', models.ManyToManyField(blank=True, to='api.subject', verbose_name='Subjects')),
            ],
            options={
                'unique_together': {('name', 'students_year', 'program', 'school')},
            },
        ),
    ]
