# Generated by Django 5.0 on 2024-01-07 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_classe_batch_remove_student_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 12, 21, 58, 136000, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
    ]
