# Generated by Django 5.0 on 2024-09-08 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_academicyeardivision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='period_division_name',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='period_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.academicyeardivision', verbose_name='Academic Year Division'),
        ),
    ]
