# Generated by Django 5.0 on 2024-11-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_graduatedclasse_graduated_class_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='linkedclasse',
            unique_together={('school', 'from_class')},
        ),
    ]
