# Generated by Django 5.0 on 2024-01-07 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_classe_create_at_classe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='delete_class',
            field=models.BooleanField(default=True, verbose_name='Admin To Delete Class'),
        ),
        migrations.AddField(
            model_name='school',
            name='delete_staff',
            field=models.BooleanField(default=True, verbose_name='Admin To Delete Staff'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 16, 38, 15, 773886, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
    ]
