# Generated by Django 5.0 on 2024-11-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_linkedclasse_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='schools',
            field=models.ManyToManyField(blank=True, to='api.school', verbose_name='Schools'),
        ),
    ]
