# Generated by Django 5.0 on 2024-09-09 12:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_classe_students_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 9), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='department',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 9), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='head',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 9), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='program',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 9), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='result',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 9), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='school',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 9), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 9), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 9), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 9), verbose_name='Attendance Date'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 9), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 9), max_length=20, verbose_name='Date Created'),
        ),
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, null=True, verbose_name='Grading Label')),
                ('range', models.CharField(max_length=20, null=True, verbose_name='Grading Range')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school', verbose_name='School')),
            ],
        ),
    ]
