# Generated by Django 5.0 on 2024-11-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_subject_schools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='level',
        ),
    ]
