# Generated by Django 5.0 on 2024-01-08 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_school_delete_class_school_delete_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='sem_1_start_date',
        ),
        migrations.AlterField(
            model_name='classe',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 9, 35, 0, 127233, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
    ]
