# Generated by Django 5.0 on 2024-01-08 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_academicyear_sem_1_start_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('name', 'students_year', 'program', 'school')},
        ),
        migrations.AlterField(
            model_name='classe',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 12, 32, 32, 164658, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
    ]
