# Generated by Django 5.0 on 2024-09-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_gradingsystem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsystem',
            name='remark',
            field=models.CharField(max_length=50, null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='gradingsystem',
            name='label',
            field=models.CharField(max_length=10, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='gradingsystem',
            name='range',
            field=models.CharField(max_length=10, null=True, verbose_name='Range'),
        ),
    ]
