# Generated by Django 5.0 on 2024-01-08 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_classe_unique_together_alter_classe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 12, 53, 46, 634152, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
    ]
