# Generated by Django 5.0 on 2024-11-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_student_date_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='staff',
            name='religion',
            field=models.CharField(default='', max_length=100, verbose_name='Religion'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email Address'),
        ),
    ]
