# Generated by Django 5.0 on 2024-01-09 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_classe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='academic_system',
            field=models.CharField(default='semester', max_length=20, verbose_name='School Academic System'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 9, 55, 38, 628211, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
    ]
