# Generated by Django 5.0 on 2024-11-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_staff_email_staff_religion_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='sch_logo',
            new_name='logo',
        ),
    ]
