# Generated by Django 5.0 on 2024-09-09 14:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_result_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_term', models.IntegerField(verbose_name='Term')),
                ('student_year', models.IntegerField(blank=True, null=True, verbose_name='Student Year')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Student's Score")),
                ('date_time', models.DateField(default=datetime.datetime(2024, 9, 9, 14, 39, 52, 112011, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='Date Created')),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.academicyear', verbose_name='Academic Year')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school', verbose_name='School')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.student', verbose_name='Student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subject', verbose_name='Subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff', verbose_name='Uploaded By')),
            ],
            options={
                'unique_together': {('student', 'subject', 'academic_year', 'academic_term', 'teacher', 'date_time')},
            },
        ),
    ]
