# Generated by Django 5.0 on 2024-01-09 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_school_academic_system_alter_classe_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='academic_system',
        ),
        migrations.AddField(
            model_name='school',
            name='semesters',
            field=models.BooleanField(default=True, verbose_name='Semester System'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 9, 58, 47, 88047, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
    ]
