# Generated by Django 5.0 on 2024-11-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_sch_logo_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='staff title'),
        ),
    ]
