# Generated by Django 5.0 on 2024-11-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_staff_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='date_enrolled',
        ),
    ]
