# Generated by Django 5.0 on 2024-01-10 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_result_student_year_alter_classe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 14, 1, 21, 418559, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
    ]
