# Generated by Django 5.0 on 2024-01-11 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_classe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 15, 48, 52, 468533, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='head',
            name='address',
            field=models.CharField(default='not set', max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='head',
            name='contact',
            field=models.CharField(default='not set', max_length=20, verbose_name='Phone No'),
        ),
        migrations.AlterField(
            model_name='head',
            name='gender',
            field=models.CharField(default='not set', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='head',
            name='nationality',
            field=models.CharField(default='GHANAIAN', max_length=50, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='head',
            name='pob',
            field=models.CharField(default='not set', max_length=50, verbose_name='Home City/Town'),
        ),
        migrations.AlterField(
            model_name='head',
            name='region',
            field=models.CharField(default='not set', max_length=50, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nationality',
            field=models.CharField(default='GHANAIAN', max_length=50, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_nationality',
            field=models.CharField(default='GHANAIAN', max_length=50, verbose_name='Nationality of Guardian'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='GHANAIAN', max_length=50, verbose_name='Nationality'),
        ),
    ]
