# Generated by Django 5.0 on 2024-11-09 09:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_staff_date_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='all_teachers_attendance',
        ),
        migrations.RemoveField(
            model_name='school',
            name='delete_class',
        ),
        migrations.RemoveField(
            model_name='school',
            name='delete_staff',
        ),
        migrations.RemoveField(
            model_name='school',
            name='head_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='head_signature',
        ),
        migrations.RemoveField(
            model_name='school',
            name='semesters',
        ),
        migrations.AddField(
            model_name='school',
            name='postal_address',
            field=models.CharField(default='', max_length=100, verbose_name="School's Postal Address"),
        ),
        migrations.AddField(
            model_name='staff',
            name='signature',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=api.models.school_image_path, verbose_name="Head Master/Mistress's Signature"),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='School Address'),
        ),
    ]
