# Generated by Django 5.0 on 2024-09-10 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_exam_student_class_alter_assessment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Assessment description'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Title Of Assessment'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Total Assessment Score'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 10), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2024, 9, 10, 12, 32, 16, 654634, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='department',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 10), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 10), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='head',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 10), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='program',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 10), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='school',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 10), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 10), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 10), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 10), verbose_name='Attendance Date'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 10), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 10), max_length=20, verbose_name='Date Created'),
        ),
    ]
