# Generated by Django 5.0 on 2024-01-11 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_classe_created_at_alter_head_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='alt_contact',
            field=models.CharField(blank=True, default='not set', max_length=15, null=True, verbose_name='Alternate Phone No'),
        ),
        migrations.AddField(
            model_name='staff',
            name='alt_contact',
            field=models.CharField(blank=True, default='not set', max_length=15, null=True, verbose_name='Alternate Phone No'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 16, 3, 27, 115391, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
    ]
