# Generated by Django 5.0 on 2024-01-12 17:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_head_alt_contact_staff_alt_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 42, 2, 230410, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_term', models.IntegerField(verbose_name='Term')),
                ('student_year', models.IntegerField(blank=True, null=True, verbose_name='Student Year')),
                ('date', models.DateField(default=datetime.date(2024, 1, 12), verbose_name='Attendance Date')),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.academicyear', verbose_name='Academic Year')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school', verbose_name='School')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.student', verbose_name='Student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subject', verbose_name='Subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff', verbose_name='Uploaded By')),
            ],
            options={
                'unique_together': {('student', 'subject', 'academic_year', 'academic_term', 'teacher', 'date')},
            },
        ),
    ]
