# Generated by Django 5.0 on 2024-09-10 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_school_has_departments_school_has_programs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='staffs_id',
            field=models.BooleanField(default=False, verbose_name='Does the school give staff ID numbers?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2024, 9, 10, 15, 3, 16, 889108, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='Date Created'),
        ),
    ]
