# Generated by Django 5.0 on 2024-01-13 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_classe_created_at_studentattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('school', 'subject', 'academic_year', 'academic_term', 'teacher', 'date')},
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='students_absent',
            field=models.ManyToManyField(related_name='students_absent', to='api.student', verbose_name='Students Absent'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='students_present',
            field=models.ManyToManyField(related_name='students_present', to='api.student', verbose_name='Students Present'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='students_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Students Year'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 16, 38, 19, 953779, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 13), verbose_name='Attendance Date'),
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='student_year',
        ),
    ]
