# Generated by Django 5.0 on 2024-09-10 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_school_staffs_id_alter_assessment_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardian',
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_first_name',
            field=models.CharField(default='none', max_length=100, verbose_name='Guardian First Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_last_name',
            field=models.CharField(default='none', max_length=100, verbose_name='Guardian Last Name'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2024, 9, 10, 15, 35, 51, 45413, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='Date Created'),
        ),
    ]
