# Generated by Django 5.0 on 2024-01-13 16:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_studentattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='students_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.classe', verbose_name='Students Class'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 16, 56, 56, 487677, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
    ]
