# Generated by Django 5.0 on 2024-01-14 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_studentattendance_students_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 17, 7, 47, 282253, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='head',
            name='date_enrolled',
            field=models.DateField(blank=True, null=True, verbose_name='Enrollment Date'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 14), verbose_name='Attendance Date'),
        ),
    ]
