# Generated by Django 5.0 on 2024-09-10 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_staffs_id_school_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2024, 9, 10, 16, 25, 8, 185669, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_gender',
            field=models.CharField(default='none', max_length=100, verbose_name='Guardian Gender'),
        ),
    ]
