# Generated by Django 5.0 on 2024-09-11 13:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_assessment_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='head_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff', verbose_name='Head Teacher'),
        ),
        migrations.AddField(
            model_name='school',
            name='all_teachers_attendance',
            field=models.BooleanField(default=False, verbose_name='Does the school require all teachers to do attendance?'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 11), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2024, 9, 11, 13, 27, 3, 235095, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='department',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 11), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 11), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='head',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 11), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='program',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 11), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='school',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 11), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 11), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 11), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 11), verbose_name='Attendance Date'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 11), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 11), max_length=20, verbose_name='Date Created'),
        ),
    ]
