# Generated by Django 5.0 on 2024-01-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_academicyear_sem_1_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicyear',
            old_name='sem_1_end_date',
            new_name='term_1_end_date',
        ),
        migrations.RenameField(
            model_name='academicyear',
            old_name='sem_2_end_date',
            new_name='term_2_end_date',
        ),
        migrations.RenameField(
            model_name='academicyear',
            old_name='sem_2_start_date',
            new_name='term_2_start_date',
        ),
        migrations.RenameField(
            model_name='academicyear',
            old_name='sem_3_end_date',
            new_name='term_3_end_date',
        ),
        migrations.RenameField(
            model_name='academicyear',
            old_name='sem_3_start_date',
            new_name='term_3_start_date',
        ),
    ]
