# Generated by Django 5.0 on 2024-01-17 10:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_rename_sem_1_end_date_academicyear_term_1_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='head_name',
            field=models.CharField(default='not set', max_length=20, verbose_name="Head Master/Mistress's Name"),
        ),
        migrations.AddField(
            model_name='school',
            name='sch_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=api.models.school_image_path, verbose_name='School Logo'),
        ),
    ]
