# Generated by Django 5.0 on 2024-09-11 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_classe_head_teacher_school_all_teachers_attendance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2024, 9, 11, 17, 27, 56, 771956, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='Date Created'),
        ),
        migrations.RemoveField(
            model_name='subjectassignment',
            name='subject',
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='subject',
            field=models.ManyToManyField(to='api.subject', verbose_name='Subject(s)'),
        ),
    ]
