# Generated by Django 5.0 on 2024-01-17 11:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_school_head_name_school_sch_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='head_signature',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=api.models.school_image_path, verbose_name="Head Master/Mistress's Signature"),
        ),
    ]
