# Generated by Django 5.0 on 2024-09-11 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_subjectassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectassignment',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2024, 9, 11, 17, 30, 16, 207839, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('teacher', 'students_class', 'academic_year', 'academic_term')},
        ),
    ]
