# Generated by Django 5.0 on 2024-09-11 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_rename_subject_subjectassignment_subjects_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('school', 'academic_year', 'academic_term', 'teacher', 'date', 'students_class')},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2024, 9, 11, 18, 23, 55, 896652, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='Date Created'),
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='subject',
        ),
    ]
