# Generated by Django 5.0 on 2024-09-12 06:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_subjectassignment_hod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 6, 24, 6, 792696, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by', to='api.staff', verbose_name='Assigned By'),
        ),
    ]
