# Generated by Django 5.0 on 2024-01-18 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_department_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 18), verbose_name='Attendance Date'),
        ),
        migrations.AlterUniqueTogether(
            name='head',
            unique_together={('head_id', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('staff_id', 'school')},
        ),
    ]
