# Generated by Django 5.0 on 2024-01-19 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_studentattendance_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 19), verbose_name='Attendance Date'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('school', 'subject', 'academic_year', 'academic_term', 'teacher', 'date', 'students_class')},
        ),
    ]
