# Generated by Django 5.0 on 2024-09-20 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_academicyear_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 20), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2024, 9, 20, 10, 49, 50, 580446, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Assessment description'),
        ),
        migrations.AlterField(
            model_name='department',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 20), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 20), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='head',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 20), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='program',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 20), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='school',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 20), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 20), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 20), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 20), verbose_name='Attendance Date'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 20), max_length=20, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 9, 20), max_length=20, verbose_name='Date Created'),
        ),
    ]
