# Generated by Django 5.0 on 2024-04-13 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_studentattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 13), verbose_name='Attendance Date'),
        ),
    ]
