# Generated by Django 5.0 on 2024-09-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_academicyear_date_created_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('student', 'subject', 'academic_year', 'academic_term', 'teacher', 'title', 'date_time')},
        ),
    ]
