# Generated by Django 5.0 on 2024-09-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_assessment_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='date_time',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('student', 'subject', 'academic_year', 'academic_term', 'teacher', 'title', 'date')},
        ),
    ]
