# Generated by Django 5.0 on 2024-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_rename_date_time_assessment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Assessment description'),
        ),
    ]
