# Generated by Django 5.0 on 2024-09-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_assessment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Assessment description'),
        ),
    ]
