nationality_to_country = {
    "Afghan": "Afghanistan",
    "Albanian": "Albania",
    "Algerian": "Algeria",
    "Andorran": "Andorra",
    "Angolan": "Angola",
    "Antiguan": "Antigua and Barbuda",
    "Argentine": "Argentina",
    "Armenian": "Armenia",
    "Australian": "Australia",
    "Austrian": "Austria",
    "Azerbaijani": "Azerbaijan",
    "Bahamian": "Bahamas",
    "Bahraini": "Bahrain",
    "Bangladeshi": "Bangladesh",
    "Barbadian": "Barbados",
    "Belarusian": "Belarus",
    "Belgian": "Belgium",
    "Belizean": "Belize",
    "Beninese": "Benin",
    "Bhutanese": "Bhutan",
    "Bolivian": "Bolivia",
    "Bosnian": "Bosnia and Herzegovina",
    "Botswanan": "Botswana",
    "Brazilian": "Brazil",
    "Bruneian": "Brunei",
    "Bulgarian": "Bulgaria",
    "Burkinabe": "Burkina Faso",
    "Burundian": "Burundi",
    "Cabo Verdean": "Cabo Verde",
    "Cambodian": "Cambodia",
    "Cameroonian": "Cameroon",
    "Canadian": "Canada",
    "Central African": "Central African Republic",
    "Chadian": "Chad",
    "Chilean": "Chile",
    "Chinese": "China",
    "Colombian": "Colombia",
    "Comorian": "Comoros",
    "Congolese": "Democratic Republic of the Congo",
    "Costa Rican": "Costa Rica",
    "Croatian": "Croatia",
    "Cuban": "Cuba",
    "Cypriot": "Cyprus",
    "Czech": "Czech Republic",
    "Danish": "Denmark",
    "Djiboutian": "Djibouti",
    "Dominican": "Dominican Republic",
    "Ecuadorian": "Ecuador",
    "Egyptian": "Egypt",
    "Salvadoran": "El Salvador",
    "Equatorial Guinean": "Equatorial Guinea",
    "Eritrean": "Eritrea",
    "Estonian": "Estonia",
    "Eswatini": "Eswatini",
    "Ethiopian": "Ethiopia",
    "Fijian": "Fiji",
    "Finnish": "Finland",
    "French": "France",
    "Gabonese": "Gabon",
    "Gambian": "Gambia",
    "Georgian": "Georgia",
    "German": "Germany",
    "Ghanaian": "Ghana",
    "Greek": "Greece",
    "Grenadian": "Grenada",
    "Guatemalan": "Guatemala",
    "Guinean": "Guinea",
    "Bissau-Guinean": "Guinea-Bissau",
    "Guyanese": "Guyana",
    "Haitian": "Haiti",
    "Honduran": "Honduras",
    "Hungarian": "Hungary",
    "Icelandic": "Iceland",
    "Indian": "India",
    "Indonesian": "Indonesia",
    "Iranian": "Iran",
    "Iraqi": "Iraq",
    "Irish": "Ireland",
    "Israeli": "Israel",
    "Italian": "Italy",
    "Ivorian": "Côte d'Ivoire",
    "Jamaican": "Jamaica",
    "Japanese": "Japan",
    "Jordanian": "Jordan",
    "Kazakh": "Kazakhstan",
    "Kenyan": "Kenya",
    "Kiribati": "Kiribati",
    "Korean": "South Korea",
    "Kosovar": "Kosovo",
    "Kuwaiti": "Kuwait",
    "Kyrgyz": "Kyrgyzstan",
    "Lao": "Laos",
    "Latvian": "Latvia",
    "Lebanese": "Lebanon",
    "Basotho": "Lesotho",
    "Liberian": "Liberia",
    "Libyan": "Libya",
    "Liechtensteiner": "Liechtenstein",
    "Lithuanian": "Lithuania",
    "Luxembourger": "Luxembourg",
    "Malagasy": "Madagascar",
    "Malawian": "Malawi",
    "Malaysian": "Malaysia",
    "Maldivian": "Maldives",
    "Malian": "Mali",
    "Maltese": "Malta",
    "Marshallese": "Marshall Islands",
    "Mauritanian": "Mauritania",
    "Mauritian": "Mauritius",
    "Mexican": "Mexico",
    "Micronesian": "Micronesia",
    "Moldovan": "Moldova",
    "Monegasque": "Monaco",
    "Mongolian": "Mongolia",
    "Montenegrin": "Montenegro",
    "Moroccan": "Morocco",
    "Mozambican": "Mozambique",
    "Namibian": "Namibia",
    "Nauruan": "Nauru",
    "Nepali": "Nepal",
    "Dutch": "Netherlands",
    "New Zealander": "New Zealand",
    "Nicaraguan": "Nicaragua",
    "Nigerien": "Niger",
    "Nigerian": "Nigeria",
    "North Macedonian": "North Macedonia",
    "Norwegian": "Norway",
    "Omani": "Oman",
    "Pakistani": "Pakistan",
    "Palauan": "Palau",
    "Palestinian": "Palestine",
    "Panamanian": "Panama",
    "Papua New Guinean": "Papua New Guinea",
    "Paraguayan": "Paraguay",
    "Peruvian": "Peru",
    "Filipino": "Philippines",
    "Polish": "Poland",
    "Portuguese": "Portugal",
    "Qatari": "Qatar",
    "Romanian": "Romania",
    "Russian": "Russia",
    "Rwandan": "Rwanda",
    "Saint Kitts and Nevis": "Saint Kitts and Nevis",
    "Saint Lucian": "Saint Lucia",
    "Vincentian": "Saint Vincent and the Grenadines",
    "Samoan": "Samoa",
    "San Marinese": "San Marino",
    "Sao Tomean": "São Tomé and Príncipe",
    "Saudi": "Saudi Arabia",
    "Senegalese": "Senegal",
    "Serbian": "Serbia",
    "Seychellois": "Seychelles",
    "Sierra Leonean": "Sierra Leone",
    "Singaporean": "Singapore",
    "Slovak": "Slovakia",
    "Slovene": "Slovenia",
    "Solomon Islander": "Solomon Islands",
    "Somali": "Somalia",
    "South African": "South Africa",
    "South Sudanese": "South Sudan",
    "Spanish": "Spain",
    "Sri Lankan": "Sri Lanka",
    "Sudanese": "Sudan",
    "Surinamese": "Suriname",
    "Swazi": "Eswatini",
    "Swedish": "Sweden",
    "Swiss": "Switzerland",
    "Syrian": "Syria",
    "Taiwanese": "Taiwan",
    "Tajik": "Tajikistan",
    "Tanzanian": "Tanzania",
    "Thai": "Thailand",
    "Timorese": "Timor-Leste",
    "Togolese": "Togo",
    "Tongan": "Tonga",
    "Trinidadian": "Trinidad and Tobago",
    "Tunisian": "Tunisia",
    "Turkish": "Turkey",
    "Turkmen": "Turkmenistan",
    "Tuvaluan": "Tuvalu",
    "Ugandan": "Uganda",
    "Ukrainian": "Ukraine",
    "Emirati": "United Arab Emirates",
    "British": "United Kingdom",
    "American": "United States",
    "Uruguayan": "Uruguay",
    "Uzbek": "Uzbekistan",
    "Vanuatuan": "Vanuatu",
    "Venezuelan": "Venezuela",
    "Vietnamese": "Vietnam",
    "Yemeni": "Yemen",
    "Zambian": "Zambia",
    "Zimbabwean": "Zimbabwe"
}
